// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EntityLayer.EntityLibrary
{
    public partial class BlogContents
    {
        public long Id { get; set; }
        public long? BlogId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte? RowStatusId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public long? DeletedById { get; set; }
        public long? CreatedById { get; set; }

        public virtual Blogs Blog { get; set; }
        public virtual SystemUsers CreatedBy { get; set; }
        public virtual SystemUsers DeletedBy { get; set; }
    }
}