// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EntityLayer.EntityLibrary
{
    public partial class Blogs
    {
        public Blogs()
        {
            BlogContents = new HashSet<BlogContents>();
        }

        public long Id { get; set; }
        public string Title { get; set; }
        public DateTime? DisplayedDate { get; set; }
        public string Description { get; set; }
        public long? CreatedById { get; set; }
        public DateTime? CreatedOn { get; set; }
        public byte? RowStatusId { get; set; }

        public virtual SystemUsers CreatedBy { get; set; }
        public virtual ICollection<BlogContents> BlogContents { get; set; }
    }
}